/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.synaptictools.iperf;

public class iPerfNative extends iPerfNativeCallbacks {
  private transient long swigCPtr;

  protected iPerfNative(long cPtr, boolean cMemoryOwn) {
    super(iPerfLibJNI.iPerfNative_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(iPerfNative obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(iPerfNative obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        iPerfLibJNI.delete_iPerfNative(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    iPerfLibJNI.iPerfNative_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    iPerfLibJNI.iPerfNative_change_ownership(this, swigCPtr, true);
  }

  public iPerfNative() {
    this(iPerfLibJNI.new_iPerfNative(), true);
    iPerfLibJNI.iPerfNative_director_connect(this, swigCPtr, true, true);
  }

  public static iPerfNative instance() {
    return new iPerfNative(iPerfLibJNI.iPerfNative_instance(), false);
  }

  public void deInit() {
    iPerfLibJNI.iPerfNative_deInit(swigCPtr, this);
  }

  public void init(String hostname, int port, String streamTemplate, int duration, int interval, boolean download, boolean useUDP, boolean json, char role) {
    iPerfLibJNI.iPerfNative_init(swigCPtr, this, hostname, port, streamTemplate, duration, interval, download, useUDP, json, role);
  }

  public int execute() {
    return iPerfLibJNI.iPerfNative_execute(swigCPtr, this);
  }

  public String getHostname() {
    return iPerfLibJNI.iPerfNative_getHostname(swigCPtr, this);
  }

  public void setHostname(String hostname) {
    iPerfLibJNI.iPerfNative_setHostname(swigCPtr, this, hostname);
  }

  public static int json_callback(SWIGTYPE_p_iperf_test test) {
    return iPerfLibJNI.iPerfNative_json_callback(SWIGTYPE_p_iperf_test.getCPtr(test));
  }

  public int getPort() {
    return iPerfLibJNI.iPerfNative_getPort(swigCPtr, this);
  }

  public void setPort(int port) {
    iPerfLibJNI.iPerfNative_setPort(swigCPtr, this, port);
  }

  public String getStreamTemplate() {
    return iPerfLibJNI.iPerfNative_getStreamTemplate(swigCPtr, this);
  }

  public void setStreamTemplate(String streamTemplate) {
    iPerfLibJNI.iPerfNative_setStreamTemplate(swigCPtr, this, streamTemplate);
  }

  public int getDuration() {
    return iPerfLibJNI.iPerfNative_getDuration(swigCPtr, this);
  }

  public void setDuration(int duration) {
    iPerfLibJNI.iPerfNative_setDuration(swigCPtr, this, duration);
  }

  public int getInterval() {
    return iPerfLibJNI.iPerfNative_getInterval(swigCPtr, this);
  }

  public void setInterval(int interval) {
    iPerfLibJNI.iPerfNative_setInterval(swigCPtr, this, interval);
  }

  public boolean isDebug() {
    return iPerfLibJNI.iPerfNative_isDebug(swigCPtr, this);
  }

  public void setDebug(boolean debug) {
    iPerfLibJNI.iPerfNative_setDebug(swigCPtr, this, debug);
  }

  public boolean isDownload() {
    return iPerfLibJNI.iPerfNative_isDownload(swigCPtr, this);
  }

  public void setDownload(boolean download) {
    iPerfLibJNI.iPerfNative_setDownload(swigCPtr, this, download);
  }

  public boolean isJson() {
    return iPerfLibJNI.iPerfNative_isJson(swigCPtr, this);
  }

  public void setJson(boolean json) {
    iPerfLibJNI.iPerfNative_setJson(swigCPtr, this, json);
  }

  public boolean isUseUDP() {
    return iPerfLibJNI.iPerfNative_isUseUDP(swigCPtr, this);
  }

  public void setUseUDP(boolean udp) {
    iPerfLibJNI.iPerfNative_setUseUDP(swigCPtr, this, udp);
  }

}
