/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.synaptictools.iperf;

public class ListDouble extends java.util.AbstractSequentialList<Double> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ListDouble(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ListDouble obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(ListDouble obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        iPerfLibJNI.delete_ListDouble(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ListDouble(java.util.Collection c) {
    this();
    java.util.ListIterator<Double> it = listIterator(0);
    // Special case the "copy constructor" here to avoid lots of cross-language calls
    for (java.lang.Object o : c) {
      it.add((Double)o);
    }
  }

  public int size() {
    return doSize();
  }

  public boolean add(Double value) {
    addLast(value);
    return true;
  }

  public java.util.ListIterator<Double> listIterator(int index) {
    return new java.util.ListIterator<Double>() {
      private Iterator pos;
      private Iterator last;

      private java.util.ListIterator<Double> init(int index) {
        if (index < 0 || index > ListDouble.this.size())
          throw new IndexOutOfBoundsException("Index: " + index);
        pos = ListDouble.this.begin();
	pos = pos.advance_unchecked(index);
        return this;
      }

      public void add(Double v) {
        // Technically we can invalidate last here, but this makes more sense
        last = ListDouble.this.insert(pos, v);
      }

      public void set(Double v) {
        if (null == last) {
          throw new IllegalStateException();
        }
        last.set_unchecked(v);
      }

      public void remove() {
        if (null == last) {
          throw new IllegalStateException();
        }
        ListDouble.this.remove(last);
        last = null;
      }

      public int previousIndex() {
        return ListDouble.this.doPreviousIndex(pos);
      }

      public int nextIndex() {
        return ListDouble.this.doNextIndex(pos);
      }

      public Double previous() {
        if (previousIndex() < 0) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.previous_unchecked();
        return last.deref_unchecked();
      }

      public Double next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.next_unchecked();
        return last.deref_unchecked();
      }

      public boolean hasPrevious() {
        // This call to previousIndex() will be much slower than the hasNext() implementation, but it's simpler like this with C++ forward iterators
        return previousIndex() != -1;
      }

      public boolean hasNext() {
        return ListDouble.this.doHasNext(pos);
      }
    }.init(index);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          iPerfLibJNI.delete_ListDouble_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void set_unchecked(double v) {
      iPerfLibJNI.ListDouble_Iterator_set_unchecked(swigCPtr, this, v);
    }
  
    public ListDouble.Iterator next_unchecked() {
      return new ListDouble.Iterator(iPerfLibJNI.ListDouble_Iterator_next_unchecked(swigCPtr, this), true);
    }
  
    public ListDouble.Iterator previous_unchecked() {
      return new ListDouble.Iterator(iPerfLibJNI.ListDouble_Iterator_previous_unchecked(swigCPtr, this), true);
    }
  
    public double deref_unchecked() {
      return iPerfLibJNI.ListDouble_Iterator_deref_unchecked(swigCPtr, this);
    }
  
    public ListDouble.Iterator advance_unchecked(int index) {
      return new ListDouble.Iterator(iPerfLibJNI.ListDouble_Iterator_advance_unchecked(swigCPtr, this, index), true);
    }
  
  }

  public ListDouble() {
    this(iPerfLibJNI.new_ListDouble__SWIG_0(), true);
  }

  public ListDouble(ListDouble other) {
    this(iPerfLibJNI.new_ListDouble__SWIG_1(ListDouble.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return iPerfLibJNI.ListDouble_isEmpty(swigCPtr, this);
  }

  public void clear() {
    iPerfLibJNI.ListDouble_clear(swigCPtr, this);
  }

  public ListDouble.Iterator remove(ListDouble.Iterator pos) {
    return new ListDouble.Iterator(iPerfLibJNI.ListDouble_remove(swigCPtr, this, ListDouble.Iterator.getCPtr(pos), pos), true);
  }

  public void removeLast() {
    iPerfLibJNI.ListDouble_removeLast(swigCPtr, this);
  }

  public void removeFirst() {
    iPerfLibJNI.ListDouble_removeFirst(swigCPtr, this);
  }

  public void addLast(double value) {
    iPerfLibJNI.ListDouble_addLast(swigCPtr, this, value);
  }

  public void addFirst(double value) {
    iPerfLibJNI.ListDouble_addFirst(swigCPtr, this, value);
  }

  private ListDouble.Iterator begin() {
    return new ListDouble.Iterator(iPerfLibJNI.ListDouble_begin(swigCPtr, this), true);
  }

  public ListDouble.Iterator end() {
    return new ListDouble.Iterator(iPerfLibJNI.ListDouble_end(swigCPtr, this), true);
  }

  private ListDouble.Iterator insert(ListDouble.Iterator pos, double value) {
    return new ListDouble.Iterator(iPerfLibJNI.ListDouble_insert(swigCPtr, this, ListDouble.Iterator.getCPtr(pos), pos, value), true);
  }

  public ListDouble(int count, double value) {
    this(iPerfLibJNI.new_ListDouble__SWIG_2(count, value), true);
  }

  private int doSize() {
    return iPerfLibJNI.ListDouble_doSize(swigCPtr, this);
  }

  private int doPreviousIndex(ListDouble.Iterator pos) {
    return iPerfLibJNI.ListDouble_doPreviousIndex(swigCPtr, this, ListDouble.Iterator.getCPtr(pos), pos);
  }

  private int doNextIndex(ListDouble.Iterator pos) {
    return iPerfLibJNI.ListDouble_doNextIndex(swigCPtr, this, ListDouble.Iterator.getCPtr(pos), pos);
  }

  private boolean doHasNext(ListDouble.Iterator pos) {
    return iPerfLibJNI.ListDouble_doHasNext(swigCPtr, this, ListDouble.Iterator.getCPtr(pos), pos);
  }

}
