/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.synaptictools.iperf;

public class StringList extends java.util.AbstractSequentialList<String> {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StringList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(StringList obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        iPerfLibJNI.delete_StringList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringList(java.util.Collection c) {
    this();
    java.util.ListIterator<String> it = listIterator(0);
    // Special case the "copy constructor" here to avoid lots of cross-language calls
    for (java.lang.Object o : c) {
      it.add((String)o);
    }
  }

  public int size() {
    return doSize();
  }

  public boolean add(String value) {
    addLast(value);
    return true;
  }

  public java.util.ListIterator<String> listIterator(int index) {
    return new java.util.ListIterator<String>() {
      private Iterator pos;
      private Iterator last;

      private java.util.ListIterator<String> init(int index) {
        if (index < 0 || index > StringList.this.size())
          throw new IndexOutOfBoundsException("Index: " + index);
        pos = StringList.this.begin();
	pos = pos.advance_unchecked(index);
        return this;
      }

      public void add(String v) {
        // Technically we can invalidate last here, but this makes more sense
        last = StringList.this.insert(pos, v);
      }

      public void set(String v) {
        if (null == last) {
          throw new IllegalStateException();
        }
        last.set_unchecked(v);
      }

      public void remove() {
        if (null == last) {
          throw new IllegalStateException();
        }
        StringList.this.remove(last);
        last = null;
      }

      public int previousIndex() {
        return StringList.this.doPreviousIndex(pos);
      }

      public int nextIndex() {
        return StringList.this.doNextIndex(pos);
      }

      public String previous() {
        if (previousIndex() < 0) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.previous_unchecked();
        return last.deref_unchecked();
      }

      public String next() {
        if (!hasNext()) {
          throw new java.util.NoSuchElementException();
        }
        last = pos;
        pos = pos.next_unchecked();
        return last.deref_unchecked();
      }

      public boolean hasPrevious() {
        // This call to previousIndex() will be much slower than the hasNext() implementation, but it's simpler like this with C++ forward iterators
        return previousIndex() != -1;
      }

      public boolean hasNext() {
        return StringList.this.doHasNext(pos);
      }
    }.init(index);
  }

  static public class Iterator {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Iterator(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Iterator obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected static long swigRelease(Iterator obj) {
      long ptr = 0;
      if (obj != null) {
        if (!obj.swigCMemOwn)
          throw new RuntimeException("Cannot release ownership as memory is not owned");
        ptr = obj.swigCPtr;
        obj.swigCMemOwn = false;
        obj.delete();
      }
      return ptr;
    }
  
    @SuppressWarnings({"deprecation", "removal"})
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          iPerfLibJNI.delete_StringList_Iterator(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void set_unchecked(String v) {
      iPerfLibJNI.StringList_Iterator_set_unchecked(swigCPtr, this, v);
    }
  
    public StringList.Iterator next_unchecked() {
      return new StringList.Iterator(iPerfLibJNI.StringList_Iterator_next_unchecked(swigCPtr, this), true);
    }
  
    public StringList.Iterator previous_unchecked() {
      return new StringList.Iterator(iPerfLibJNI.StringList_Iterator_previous_unchecked(swigCPtr, this), true);
    }
  
    public String deref_unchecked() {
      return iPerfLibJNI.StringList_Iterator_deref_unchecked(swigCPtr, this);
    }
  
    public StringList.Iterator advance_unchecked(int index) {
      return new StringList.Iterator(iPerfLibJNI.StringList_Iterator_advance_unchecked(swigCPtr, this, index), true);
    }
  
  }

  public StringList() {
    this(iPerfLibJNI.new_StringList__SWIG_0(), true);
  }

  public StringList(StringList other) {
    this(iPerfLibJNI.new_StringList__SWIG_1(StringList.getCPtr(other), other), true);
  }

  public boolean isEmpty() {
    return iPerfLibJNI.StringList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    iPerfLibJNI.StringList_clear(swigCPtr, this);
  }

  public StringList.Iterator remove(StringList.Iterator pos) {
    return new StringList.Iterator(iPerfLibJNI.StringList_remove(swigCPtr, this, StringList.Iterator.getCPtr(pos), pos), true);
  }

  public void removeLast() {
    iPerfLibJNI.StringList_removeLast(swigCPtr, this);
  }

  public void removeFirst() {
    iPerfLibJNI.StringList_removeFirst(swigCPtr, this);
  }

  public void addLast(String value) {
    iPerfLibJNI.StringList_addLast(swigCPtr, this, value);
  }

  public void addFirst(String value) {
    iPerfLibJNI.StringList_addFirst(swigCPtr, this, value);
  }

  private StringList.Iterator begin() {
    return new StringList.Iterator(iPerfLibJNI.StringList_begin(swigCPtr, this), true);
  }

  public StringList.Iterator end() {
    return new StringList.Iterator(iPerfLibJNI.StringList_end(swigCPtr, this), true);
  }

  private StringList.Iterator insert(StringList.Iterator pos, String value) {
    return new StringList.Iterator(iPerfLibJNI.StringList_insert(swigCPtr, this, StringList.Iterator.getCPtr(pos), pos, value), true);
  }

  public StringList(int count, String value) {
    this(iPerfLibJNI.new_StringList__SWIG_2(count, value), true);
  }

  private int doSize() {
    return iPerfLibJNI.StringList_doSize(swigCPtr, this);
  }

  private int doPreviousIndex(StringList.Iterator pos) {
    return iPerfLibJNI.StringList_doPreviousIndex(swigCPtr, this, StringList.Iterator.getCPtr(pos), pos);
  }

  private int doNextIndex(StringList.Iterator pos) {
    return iPerfLibJNI.StringList_doNextIndex(swigCPtr, this, StringList.Iterator.getCPtr(pos), pos);
  }

  private boolean doHasNext(StringList.Iterator pos) {
    return iPerfLibJNI.StringList_doHasNext(swigCPtr, this, StringList.Iterator.getCPtr(pos), pos);
  }

}
