/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_iPerfLib_WRAP_H_
#define SWIG_iPerfLib_WRAP_H_

class SwigDirector_iPerfNativeCallbacks : public iPerfNativeCallbacks, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_iPerfNativeCallbacks(JNIEnv *jenv);
    virtual ~SwigDirector_iPerfNativeCallbacks();
    virtual void onAppendResult(std::string result);
    virtual void onClearResult();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};

class SwigDirector_iPerfNative : public iPerfNative, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_iPerfNative(JNIEnv *jenv);
    virtual ~SwigDirector_iPerfNative();
    virtual void onAppendResult(std::string result);
    virtual void onClearResult();
public:
    bool swig_overrides(int n) {
      return (n < 2 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<2> swig_override;
};


#endif
