#define PACKAGE_NAME        "iperf"
#define PACKAGE_VERSION     "3.1.6"
#define IPERF_VERSION       "3.1.6"
#define PACKAGE_STRING      "iperf 3.1.6"
#define PACKAGE_BUGREPORT   "https://github.com/esnet/iperf"
#define PACKAGE_TARNAME     "iperf"
#define PACKAGE_URL         "http://software.es.net/iperf/"
